name: AdvancedMultiLanguage
main: me.smessie.MultiLanguage.bukkit.Main
version: ${project.version}
author: smessie
website: http://smessie.com
description: An extensive MultiLanguage Plugin with dev's API!
commands:
  language:
    default: true
    description: English language command.
    usage: /Language <language>
  langue:
    default: true
    description: French language command.
    usage: /langue <langue>
  sprache:
    default: true
    description: German language command.
    usage: /sprache <sprache>
  taal:
    default: true
    description: Dutch language command.
    usage: /taal <taal>
  idioma:
    default: true
    description: Spanish language command.
    usage: /idioma <idioma>
  язык:
    default: true
    description: Russian language command.
    usage: /язык <язык>
  valoda:
    default: true
    description: Latvian language command.
    usage: /valoda <valoda>
  sprog:
    default: true
    description: Denis language command.
    usage: /sprog <sprog>
  език:
    default: true
    description: Bulgarian language command.
    usage: /език <език>
  语言:
    default: true
    description: Chinese language command.
    usage: /语言 <语言>
  nyelv:
    default: true
    description: Hungarian language command.
    usage: /nyelv <nyelv>
  lingua:
    default: true
    description: Italian language command.
    usage: /lingua <lingua>
  język:
    default: true
    description: Polish language command.
    usage: /język <język>