name: AdvancedMultiLanguage
main: me.smessie.MultiLanguage.bukkit.Main
version: ${project.version}
author: smessie
website: https://smessie.com
description: An extensive MultiLanguage Plugin with dev's API!
commands:
  language:
    default: true
    description: Language command.
    usage: /Language <language>
    aliases:
      - langue
      - sprache
      - taal
      - idioma
      - язык
      - valoda
      - sprog
      - език
      - 语言
      - nyelv
      - lingua
      - język
      - linguagem
      - jezik
      - kalba
      - dil
      - jazyk
      - 언어
      - limba